// constants.js
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const SIGNUPSUCCESS = "SIGNUPSUCCESS"
export const SIGNUPFAIL = "SIGNUPFAIL"
export const SIGNUPREQUEST = "SIGNUPREQUEST"

export const FETCHALLUSER = "FETCHALLUSER"
export const SETADMIN = "SETADMIN"

export const PRODUCTCREATED = "PRODUCTCREATED"
export const ALLPRODUCT = "ALLPRODUCT"
export const FILTERPRODUCT = "FILTERPRODUCT"
export const GETALLSLIDERS = "GETALLSLIDERS"
export const SLIDERCREATED = "SLIDERCREATED"